name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 UTC 0 点运行一次（北京时间早上 8 点）
  workflow_dispatch:       # 手动触发按钮

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add upstream
        run: git remote add upstream https://github.com/qiankunli/qiankunli.github.io.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/master --allow-unrelated-histories || true
        # 如果原仓库是 master 分支，把 main 改成 master

      - name: Push changes
        run: git push origin master
